### ISSUE TITLE
Not able to open GWSETUP

### ISSUE THREAD

**Issue by Flyingfufu** [callumgare/geneweb-docker-image#1] opened 2023-10-15 18:02 UTC
Hello,

First of all, thanks for your nice docker image.

Geneweb is woking fine, except the gwsetup page, which I'm not able to open. I've set the "admin" computer IP address in the env. but despite multiple tests, no change. Also, no log file gets recorded, not allowing me to investigate deeper the possible reason for this issue... I confirm that all folder permission have been set as recommended.

Looking forward to a solution, I will welcome any help or tips !

Regards,

**Comment by callumgare** [comment] 2023-10-18 21:33
When you say you're not able to open it what does that mean? Does the page just keep loading forever? Do you get an error message? If so is it an error message from your browser or from geneweb?

If the allowed IP address is incorrect then you should see this error message:
<img width="758" alt="Screenshot 2023-10-19 at 08 29 11" src="https://github.com/callumgare/geneweb-docker-image/assets/346340/d5f55212-9b9c-4210-bd02-2276aa2d8435">
So if you don't see that then it sounds like there's a different issue but without more details and a way for me to reproduce the issue I can't say what that issue might be.

**Comment by Flyingfufu** [comment] 2023-10-18 21:59
Thanks for your feedback.

I've setup the ip in the "only.txt" file, so don't get the "Forbidden access" page. I simply get an ERR_CONNECTION_REFUSED page in any browser, as attached 
![image](https://github.com/callumgare/geneweb-docker-image/assets/45739159/851c0995-5936-4370-824f-84c1d0117a03)

Here also my compose file 
![image](https://github.com/callumgare/geneweb-docker-image/assets/45739159/83021fc1-bff8-4688-a48a-2e0e65d0ee5d)

Last but not least, I cannot no investigate any log files as I don't get any created. I'm therefore not able to understand the potential root cause as I'm blind. The docker log don't give me more info
![image](https://github.com/callumgare/geneweb-docker-image/assets/45739159/a1a2809c-92e1-45ab-884a-1eaaf92b0101)

Any idea, guidance will be welcome and appreciated.

Best regards

**Comment by callumgare** [comment] 2023-10-19 00:48
Intersting, not quite sure what's going on there. However as I was looking into it actually came across this PR to setup an official geneweb image: https://github.com/geneweb/geneweb/pull/1395 

That image seems a lot more thought out and robust than what I’ve thrown together (I initially made this one because I wanted to play around with geneweb by setting it up in my self hosted environment and there wasn’t an official image or a 3rd party image on docker hub that looked recent). So I think I'm actually going to archive this repo and point people to that one.

It’s obviously not merged yet but the CI of repo that the PR is from is setup to push an image to the GitHub docker repository so you can use that image and then hopefully it will get merged at some point and then there'll be an official one. This is the docker compose file I used to get it running: https://github.com/geneweb/geneweb/pull/1395#issuecomment-1769711477

**Closed as completed by callumgare** 2023-10-19 00:48 UTC

**Comment by Flyingfufu** [comment] 2023-10-19 19:02
Thanks for the time you spent on it.
As recommended, I've now installed the above docker image. All is working well now.

Thanks for your work that was very useful and handy for quite some time. Appreciate the work done by guys like you, helping other like me to have an easier life !

All the best
